### ISSUE TITLE
jarvis does not start after update iobroker to 8.0.1

### ISSUE THREAD

**Issue by delta2308151984** [Zefau/ioBroker.jarvis#2393]
Here is the error log:

2023-07-09 17:11:19.227  - [32minfo[39m: host.ds-delta23 instance system.adapter.jarvis.0 started with pid 2636
2023-07-09 17:11:19.854  - [32minfo[39m: host.ds-delta23 stopInstance system.adapter.jarvis.0 (force=false, process=true)
2023-07-09 17:11:19.948  - [32minfo[39m: host.ds-delta23 stopInstance system.adapter.jarvis.0 send kill signal
2023-07-09 17:11:20.953  - [32minfo[39m: host.ds-delta23 stopInstance system.adapter.jarvis.0 killing pid 2636
2023-07-09 17:11:21.036  - [33mwarn[39m: host.ds-delta23 instance system.adapter.jarvis.0 terminated due to SIGTERM
2023-07-09 17:11:21.037  - [32minfo[39m: host.ds-delta23 instance system.adapter.jarvis.0 terminated with code null ()
2023-07-09 17:11:23.180  - [32minfo[39m: host.ds-delta23 instance system.adapter.jarvis.0 started with pid 2655
2023-07-09 17:11:24.637  - [31merror[39m: host.ds-delta23 Caught by controller[0]: node:internal/modules/cjs/loader:1080
2023-07-09 17:11:24.637  - [31merror[39m: host.ds-delta23 Caught by controller[0]:   throw err;
2023-07-09 17:11:24.638  - [31merror[39m: host.ds-delta23 Caught by controller[0]:   ^
2023-07-09 17:11:24.638  - [31merror[39m: host.ds-delta23 Caught by controller[0]: Error: Cannot find module 'fs-extra'
2023-07-09 17:11:24.638  - [31merror[39m: host.ds-delta23 Caught by controller[0]: Require stack:
2023-07-09 17:11:24.639  - [31merror[39m: host.ds-delta23 Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.jarvis/lib/server.js
2023-07-09 17:11:24.639  - [31merror[39m: host.ds-delta23 Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.jarvis/jarvis.js
2023-07-09 17:11:24.639  - [31merror[39m: host.ds-delta23 Caught by controller[0]:     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
2023-07-09 17:11:24.639  - [31merror[39m: host.ds-delta23 Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:922:27)
2023-07-09 17:11:24.639  - [31merror[39m: host.ds-delta23 Caught by controller[0]:     at Module.require (node:internal/modules/cjs/loader:1143:19)
2023-07-09 17:11:24.639  - [31merror[39m: host.ds-delta23 Caught by controller[0]:     at require (node:internal/modules/cjs/helpers:110:18)
2023-07-09 17:11:24.639  - [31merror[39m: host.ds-delta23 Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.jarvis/lib/server.js:1:11)
2023-07-09 17:11:24.639  - [31merror[39m: host.ds-delta23 Caught by controller[0]:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
2023-07-09 17:11:24.639  - [31merror[39m: host.ds-delta23 Caught by controller[0]:     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
2023-07-09 17:11:24.640  - [31merror[39m: host.ds-delta23 Caught by controller[0]:     at Module.load (node:internal/modules/cjs/loader:1119:32)
2023-07-09 17:11:24.640  - [31merror[39m: host.ds-delta23 Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:960:12)
2023-07-09 17:11:24.640  - [31merror[39m: host.ds-delta23 Caught by controller[0]:     at Module.require (node:internal/modules/cjs/loader:1143:19) {
2023-07-09 17:11:24.640  - [31merror[39m: host.ds-delta23 Caught by controller[0]:   code: 'MODULE_NOT_FOUND',
2023-07-09 17:11:24.640  - [31merror[39m: host.ds-delta23 Caught by controller[0]:   requireStack: [
2023-07-09 17:11:24.640  - [31merror[39m: host.ds-delta23 Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.jarvis/lib/server.js',
2023-07-09 17:11:24.640  - [31merror[39m: host.ds-delta23 Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.jarvis/jarvis.js'
2023-07-09 17:11:24.640  - [31merror[39m: host.ds-delta23 Caught by controller[0]:   ]
2023-07-09 17:11:24.640  - [31merror[39m: host.ds-delta23 Caught by controller[0]: }
2023-07-09 17:11:24.641  - [31merror[39m: host.ds-delta23 Caught by controller[0]: Node.js v18.16.1
2023-07-09 17:11:24.641  - [31merror[39m: host.ds-delta23 instance system.adapter.jarvis.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2023-07-09 17:11:24.641  - [32minfo[39m: host.ds-delta23 Rebuild for adapter system.adapter.jarvis.0 not successful in 3 tries. Adapter will not be restarted again. Please execute "npm install --production" in adapter directory manually.

I need some help to fix this problem.
Do jarvis work with node 18.16.1?

**Comment by mcuiobroker** [comment]
Please open an Thread in iobroker-Forum to check the system.
Which Version of jarvis?

https://forum.iobroker.net/recent

**Comment by delta2308151984** [comment]
It is jarvis 3.12. The latest adapter in iobroker

**Comment by mcuiobroker** [comment]
v3.1.2 works with nodejs v18.16.1.

**Comment by delta2308151984** [comment]
I have solved the problem.
I was on iobroker 7.1.1 and would update to 8.0.1. I made a backup on the conlsole with "iobroker backup".
After updating iobroker to 8.0.1 and restore with the command "iobroker restore 0" i got the error message.
The solution was to restore jarvis with the backitup adapter. Now it works.

**Comment by mcuiobroker** [comment]
Where do you get the version number? 7.1.1 or 8.0.1?
